import * as React from 'react'

export type Cabanaico = {
    small?: boolean,
    className?: string
}

export var IconActivityOutline: React.ComponentType<Cabanaico>
export var IconAlertCircleOutline: React.ComponentType<Cabanaico>
export var IconAlertTriangleOutline: React.ComponentType<Cabanaico>
export var IconArchiveOutline: React.ComponentType<Cabanaico>
export var IconArrowBackOutline: React.ComponentType<Cabanaico>
export var IconArrowCircleDownOutline: React.ComponentType<Cabanaico>
export var IconArrowCircleLeftOutline: React.ComponentType<Cabanaico>
export var IconArrowCircleRightOutline: React.ComponentType<Cabanaico>
export var IconArrowCircleUpOutline: React.ComponentType<Cabanaico>
export var IconArrowDownOutline: React.ComponentType<Cabanaico>
export var IconArrowDownwardOutline: React.ComponentType<Cabanaico>
export var IconArrowForwardOutline: React.ComponentType<Cabanaico>
export var IconArrowIosBackOutline: React.ComponentType<Cabanaico>
export var IconArrowIosDownwardOutline: React.ComponentType<Cabanaico>
export var IconArrowIosForwardOutline: React.ComponentType<Cabanaico>
export var IconArrowIosUpwardOutline: React.ComponentType<Cabanaico>
export var IconArrowLeftOutline: React.ComponentType<Cabanaico>
export var IconArrowRightOutline: React.ComponentType<Cabanaico>
export var IconArrowUpOutline: React.ComponentType<Cabanaico>
export var IconArrowUpwardOutline: React.ComponentType<Cabanaico>
export var IconArrowheadDownOutline: React.ComponentType<Cabanaico>
export var IconArrowheadLeftOutline: React.ComponentType<Cabanaico>
export var IconArrowheadRightOutline: React.ComponentType<Cabanaico>
export var IconArrowheadUpOutline: React.ComponentType<Cabanaico>
export var IconAtOutline: React.ComponentType<Cabanaico>
export var IconAttach2Outline: React.ComponentType<Cabanaico>
export var IconAttachOutline: React.ComponentType<Cabanaico>
export var IconAwardOutline: React.ComponentType<Cabanaico>
export var IconBackspaceOutline: React.ComponentType<Cabanaico>
export var IconBarChart2Outline: React.ComponentType<Cabanaico>
export var IconBarChartOutline: React.ComponentType<Cabanaico>
export var IconBatteryOutline: React.ComponentType<Cabanaico>
export var IconBehanceOutline: React.ComponentType<Cabanaico>
export var IconBellOffOutline: React.ComponentType<Cabanaico>
export var IconBellOutline: React.ComponentType<Cabanaico>
export var IconBluetoothOutline: React.ComponentType<Cabanaico>
export var IconBookOpenOutline: React.ComponentType<Cabanaico>
export var IconBookOutline: React.ComponentType<Cabanaico>
export var IconBookmarkOutline: React.ComponentType<Cabanaico>
export var IconBriefcaseOutline: React.ComponentType<Cabanaico>
export var IconBrowserOutline: React.ComponentType<Cabanaico>
export var IconBrushOutline: React.ComponentType<Cabanaico>
export var IconBulbOutline: React.ComponentType<Cabanaico>
export var IconCalendarOutline: React.ComponentType<Cabanaico>
export var IconCameraOutline: React.ComponentType<Cabanaico>
export var IconCarOutline: React.ComponentType<Cabanaico>
export var IconCastOutline: React.ComponentType<Cabanaico>
export var IconChargingOutline: React.ComponentType<Cabanaico>
export var IconCheckmarkCircle2Outline: React.ComponentType<Cabanaico>
export var IconCheckmarkCircleOutline: React.ComponentType<Cabanaico>
export var IconCheckmarkOutline: React.ComponentType<Cabanaico>
export var IconCheckmarkSquare2Outline: React.ComponentType<Cabanaico>
export var IconCheckmarkSquareOutline: React.ComponentType<Cabanaico>
export var IconChevronDownOutline: React.ComponentType<Cabanaico>
export var IconChevronLeftOutline: React.ComponentType<Cabanaico>
export var IconChevronRightOutline: React.ComponentType<Cabanaico>
export var IconChevronUpOutline: React.ComponentType<Cabanaico>
export var IconClipboardOutline: React.ComponentType<Cabanaico>
export var IconClockOutline: React.ComponentType<Cabanaico>
export var IconCloseCircleOutline: React.ComponentType<Cabanaico>
export var IconCloseOutline: React.ComponentType<Cabanaico>
export var IconCloseSquareOutline: React.ComponentType<Cabanaico>
export var IconCloudDownloadOutline: React.ComponentType<Cabanaico>
export var IconCloudUploadOutline: React.ComponentType<Cabanaico>
export var IconCodeDownloadOutline: React.ComponentType<Cabanaico>
export var IconCodeOutline: React.ComponentType<Cabanaico>
export var IconCollapseOutline: React.ComponentType<Cabanaico>
export var IconColorPaletteOutline: React.ComponentType<Cabanaico>
export var IconColorPickerOutline: React.ComponentType<Cabanaico>
export var IconCompassOutline: React.ComponentType<Cabanaico>
export var IconCopyOutline: React.ComponentType<Cabanaico>
export var IconCornerDownLeftOutline: React.ComponentType<Cabanaico>
export var IconCornerDownRightOutline: React.ComponentType<Cabanaico>
export var IconCornerLeftDownOutline: React.ComponentType<Cabanaico>
export var IconCornerLeftUpOutline: React.ComponentType<Cabanaico>
export var IconCornerRightDownOutline: React.ComponentType<Cabanaico>
export var IconCornerRightUpOutline: React.ComponentType<Cabanaico>
export var IconCornerUpLeftOutline: React.ComponentType<Cabanaico>
export var IconCornerUpRightOutline: React.ComponentType<Cabanaico>
export var IconCreditCardOutline: React.ComponentType<Cabanaico>
export var IconCropOutline: React.ComponentType<Cabanaico>
export var IconCubeOutline: React.ComponentType<Cabanaico>
export var IconDiagonalArrowLeftDownOutline: React.ComponentType<Cabanaico>
export var IconDiagonalArrowLeftUpOutline: React.ComponentType<Cabanaico>
export var IconDiagonalArrowRightDownOutline: React.ComponentType<Cabanaico>
export var IconDiagonalArrowRightUpOutline: React.ComponentType<Cabanaico>
export var IconDoneAllOutline: React.ComponentType<Cabanaico>
export var IconDownloadOutline: React.ComponentType<Cabanaico>
export var IconDropletOffOutline: React.ComponentType<Cabanaico>
export var IconDropletOutline: React.ComponentType<Cabanaico>
export var IconEdit2Outline: React.ComponentType<Cabanaico>
export var IconEditOutline: React.ComponentType<Cabanaico>
export var IconEmailOutline: React.ComponentType<Cabanaico>
export var IconExpandOutline: React.ComponentType<Cabanaico>
export var IconExternalLinkOutline: React.ComponentType<Cabanaico>
export var IconEyeOff2Outline: React.ComponentType<Cabanaico>
export var IconEyeOffOutline: React.ComponentType<Cabanaico>
export var IconEyeOutline: React.ComponentType<Cabanaico>
export var IconFacebookOutline: React.ComponentType<Cabanaico>
export var IconFileAddOutline: React.ComponentType<Cabanaico>
export var IconFileOutline: React.ComponentType<Cabanaico>
export var IconFileRemoveOutline: React.ComponentType<Cabanaico>
export var IconFileTextOutline: React.ComponentType<Cabanaico>
export var IconFilmOutline: React.ComponentType<Cabanaico>
export var IconFlagOutline: React.ComponentType<Cabanaico>
export var IconFlashOffOutline: React.ComponentType<Cabanaico>
export var IconFlashOutline: React.ComponentType<Cabanaico>
export var IconFlip2Outline: React.ComponentType<Cabanaico>
export var IconFlipOutline: React.ComponentType<Cabanaico>
export var IconFolderAddOutline: React.ComponentType<Cabanaico>
export var IconFolderOutline: React.ComponentType<Cabanaico>
export var IconFolderRemoveOutline: React.ComponentType<Cabanaico>
export var IconFunnelOutline: React.ComponentType<Cabanaico>
export var IconGiftOutline: React.ComponentType<Cabanaico>
export var IconGithubOutline: React.ComponentType<Cabanaico>
export var IconGlobe2Outline: React.ComponentType<Cabanaico>
export var IconGlobeOutline: React.ComponentType<Cabanaico>
export var IconGoogleOutline: React.ComponentType<Cabanaico>
export var IconGridOutline: React.ComponentType<Cabanaico>
export var IconHardDriveOutline: React.ComponentType<Cabanaico>
export var IconHashOutline: React.ComponentType<Cabanaico>
export var IconHeadphonesOutline: React.ComponentType<Cabanaico>
export var IconHeartOutline: React.ComponentType<Cabanaico>
export var IconHomeOutline: React.ComponentType<Cabanaico>
export var IconImageOutline: React.ComponentType<Cabanaico>
export var IconInboxOutline: React.ComponentType<Cabanaico>
export var IconInfoOutline: React.ComponentType<Cabanaico>
export var IconKeypadOutline: React.ComponentType<Cabanaico>
export var IconLayersOutline: React.ComponentType<Cabanaico>
export var IconLayoutOutline: React.ComponentType<Cabanaico>
export var IconLink2Outline: React.ComponentType<Cabanaico>
export var IconLinkOutline: React.ComponentType<Cabanaico>
export var IconLinkedinOutline: React.ComponentType<Cabanaico>
export var IconListOutline: React.ComponentType<Cabanaico>
export var IconLoaderOutline: React.ComponentType<Cabanaico>
export var IconLockOutline: React.ComponentType<Cabanaico>
export var IconLogInOutline: React.ComponentType<Cabanaico>
export var IconLogOutOutline: React.ComponentType<Cabanaico>
export var IconMapOutline: React.ComponentType<Cabanaico>
export var IconMaximizeOutline: React.ComponentType<Cabanaico>
export var IconMenu2Outline: React.ComponentType<Cabanaico>
export var IconMenuArrowOutline: React.ComponentType<Cabanaico>
export var IconMenuOutline: React.ComponentType<Cabanaico>
export var IconMessageCircleOutline: React.ComponentType<Cabanaico>
export var IconMessageSquareOutline: React.ComponentType<Cabanaico>
export var IconMicOffOutline: React.ComponentType<Cabanaico>
export var IconMicOutline: React.ComponentType<Cabanaico>
export var IconMinimizeOutline: React.ComponentType<Cabanaico>
export var IconMinusCircleOutline: React.ComponentType<Cabanaico>
export var IconMinusOutline: React.ComponentType<Cabanaico>
export var IconMinusSquareOutline: React.ComponentType<Cabanaico>
export var IconMonitorOutline: React.ComponentType<Cabanaico>
export var IconMoonOutline: React.ComponentType<Cabanaico>
export var IconMoreHorizontalOutline: React.ComponentType<Cabanaico>
export var IconMoreVerticalOutline: React.ComponentType<Cabanaico>
export var IconMoveOutline: React.ComponentType<Cabanaico>
export var IconMusicOutline: React.ComponentType<Cabanaico>
export var IconNavigation2Outline: React.ComponentType<Cabanaico>
export var IconNavigationOutline: React.ComponentType<Cabanaico>
export var IconNpmOutline: React.ComponentType<Cabanaico>
export var IconOptions2Outline: React.ComponentType<Cabanaico>
export var IconOptionsOutline: React.ComponentType<Cabanaico>
export var IconPantoneOutline: React.ComponentType<Cabanaico>
export var IconPaperPlaneOutline: React.ComponentType<Cabanaico>
export var IconPauseCircleOutline: React.ComponentType<Cabanaico>
export var IconPeopleOutline: React.ComponentType<Cabanaico>
export var IconPercentOutline: React.ComponentType<Cabanaico>
export var IconPersonAddOutline: React.ComponentType<Cabanaico>
export var IconPersonDeleteOutline: React.ComponentType<Cabanaico>
export var IconPersonDoneOutline: React.ComponentType<Cabanaico>
export var IconPersonOutline: React.ComponentType<Cabanaico>
export var IconPersonRemoveOutline: React.ComponentType<Cabanaico>
export var IconPhoneCallOutline: React.ComponentType<Cabanaico>
export var IconPhoneMissedOutline: React.ComponentType<Cabanaico>
export var IconPhoneOffOutline: React.ComponentType<Cabanaico>
export var IconPhoneOutline: React.ComponentType<Cabanaico>
export var IconPieChartOutline: React.ComponentType<Cabanaico>
export var IconPinOutline: React.ComponentType<Cabanaico>
export var IconPlayCircleOutline: React.ComponentType<Cabanaico>
export var IconPlusCircleOutline: React.ComponentType<Cabanaico>
export var IconPlusOutline: React.ComponentType<Cabanaico>
export var IconPlusSquareOutline: React.ComponentType<Cabanaico>
export var IconPowerOutline: React.ComponentType<Cabanaico>
export var IconPricetagsOutline: React.ComponentType<Cabanaico>
export var IconPrinterOutline: React.ComponentType<Cabanaico>
export var IconQuestionMarkCircleOutline: React.ComponentType<Cabanaico>
export var IconQuestionMarkOutline: React.ComponentType<Cabanaico>
export var IconRadioButtonOffOutline: React.ComponentType<Cabanaico>
export var IconRadioButtonOnOutline: React.ComponentType<Cabanaico>
export var IconRadioOutline: React.ComponentType<Cabanaico>
export var IconRecordingOutline: React.ComponentType<Cabanaico>
export var IconRefreshOutline: React.ComponentType<Cabanaico>
export var IconRepeatOutline: React.ComponentType<Cabanaico>
export var IconRewindLeftOutline: React.ComponentType<Cabanaico>
export var IconRewindRightOutline: React.ComponentType<Cabanaico>
export var IconSaveOutline: React.ComponentType<Cabanaico>
export var IconScissorsOutline: React.ComponentType<Cabanaico>
export var IconSearchOutline: React.ComponentType<Cabanaico>
export var IconSettings2Outline: React.ComponentType<Cabanaico>
export var IconSettingsOutline: React.ComponentType<Cabanaico>
export var IconShakeOutline: React.ComponentType<Cabanaico>
export var IconShareOutline: React.ComponentType<Cabanaico>
export var IconShieldOffOutline: React.ComponentType<Cabanaico>
export var IconShieldOutline: React.ComponentType<Cabanaico>
export var IconShoppingBagOutline: React.ComponentType<Cabanaico>
export var IconShoppingCartOutline: React.ComponentType<Cabanaico>
export var IconShuffle2Outline: React.ComponentType<Cabanaico>
export var IconShuffleOutline: React.ComponentType<Cabanaico>
export var IconSkipBackOutline: React.ComponentType<Cabanaico>
export var IconSkipForwardOutline: React.ComponentType<Cabanaico>
export var IconSlashOutline: React.ComponentType<Cabanaico>
export var IconSmartphoneOutline: React.ComponentType<Cabanaico>
export var IconSpeakerOutline: React.ComponentType<Cabanaico>
export var IconSquareOutline: React.ComponentType<Cabanaico>
export var IconStarOutline: React.ComponentType<Cabanaico>
export var IconStopCircleOutline: React.ComponentType<Cabanaico>
export var IconSunOutline: React.ComponentType<Cabanaico>
export var IconSwapOutline: React.ComponentType<Cabanaico>
export var IconSyncOutline: React.ComponentType<Cabanaico>
export var IconTextOutline: React.ComponentType<Cabanaico>
export var IconThermometerMinusOutline: React.ComponentType<Cabanaico>
export var IconThermometerOutline: React.ComponentType<Cabanaico>
export var IconThermometerPlusOutline: React.ComponentType<Cabanaico>
export var IconToggleLeftOutline: React.ComponentType<Cabanaico>
export var IconToggleRightOutline: React.ComponentType<Cabanaico>
export var IconTrash2Outline: React.ComponentType<Cabanaico>
export var IconTrashOutline: React.ComponentType<Cabanaico>
export var IconTrendingDownOutline: React.ComponentType<Cabanaico>
export var IconTrendingUpOutline: React.ComponentType<Cabanaico>
export var IconTvOutline: React.ComponentType<Cabanaico>
export var IconTwitterOutline: React.ComponentType<Cabanaico>
export var IconUmbrellaOutline: React.ComponentType<Cabanaico>
export var IconUndoOutline: React.ComponentType<Cabanaico>
export var IconUnlockOutline: React.ComponentType<Cabanaico>
export var IconUploadOutline: React.ComponentType<Cabanaico>
export var IconVideoOffOutline: React.ComponentType<Cabanaico>
export var IconVideoOutline: React.ComponentType<Cabanaico>
export var IconVolumeDownOutline: React.ComponentType<Cabanaico>
export var IconVolumeMuteOutline: React.ComponentType<Cabanaico>
export var IconVolumeOffOutline: React.ComponentType<Cabanaico>
export var IconVolumeUpOutline: React.ComponentType<Cabanaico>
export var IconWifiOffOutline: React.ComponentType<Cabanaico>
export var IconWifiOutline: React.ComponentType<Cabanaico>
 